# Generated by Django 4.1.4 on 2023-06-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
