# Generated by Django 4.1.4 on 2023-05-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='cart')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
