# Generated by Django 4.1.4 on 2023-06-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
    ]
