# Generated by Django 4.1.4 on 2023-06-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=75, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=500)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='order')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Order has been shiped', 'Order has been shiped'), ('On the way', 'On the way'), ('Dilivered', 'Dilivered')], default='Order has been placed', max_length=50)),
            ],
            options={
                'db_table': 'orderdetails',
            },
        ),
    ]
