# Generated by Django 4.1.4 on 2023-06-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='email',
            field=models.EmailField(max_length=75),
        ),
    ]
