# Generated by Django 4.1.4 on 2023-06-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderdetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
    ]
