# Generated by Django 4.1.4 on 2023-06-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(choices=[('Order has been placed', 'Order has been placed'), ('Order has been shiped', 'Order has been shiped'), ('Your order has been recieved in the hub nearest to you', 'Your order has been recieved in the hub nearest to you'), ('Out for delivery', 'Out for delivery'), ('Dilivered', 'Dilivered')], default='Order has been placed', max_length=100),
        ),
    ]
