# Generated by Django 4.1.4 on 2023-06-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderdetails_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='username',
        ),
    ]
